spring:
  application:
    name: query-service
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s

server:
  port: 9006

logging:
  level:
    org.springframework.data.elasticsearch: INFO
    org.example.queryservice: INFO
